default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: global_api_dev

test:
  <<: *default
  database: global_api_test

production:
  <<: *default
  database: db/production.sqlite3
